# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file ''
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QWidget


class Ui_grid(QWidget):
    def __init__(self, na, alt):
        
        super(Ui_grid, self).__init__()
        # 将UI界面布局到Demo上；
        # 初始化
        self.setupUi(self, na, alt)
    
    def setupUi(self, uiGrid, na, alt):
        uiGrid.setObjectName("uiGrid")
        uiGrid.resize(696, 370)
        uiGrid.setStyleSheet(
                "QPushButton:hover{  \n"
                "    padding-bottom:4px; \n"
                "}"
        )
        # verticalLayout_list_reco from 的格局
        self.verticalLayout_list_reco = QtWidgets.QVBoxLayout(uiGrid)
        self.verticalLayout_list_reco.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_list_reco.setSpacing(0)
        self.verticalLayout_list_reco.setObjectName("verticalLayout_list_{}".format(na))
        self.add_sheet(uiGrid, na, alt)
    
    def add_sheet(self, uiGrid, na, alt):
        self.frame_list = []
        self.horizontalLayout_list = []
        self.splitter_list = []
        self.pushButton_list = []
        self.label_list = []
        self.tr_list = []

        n = len(alt)
        n = int(n / 4)
        l = 0
        for i in range(n):
            frame_list = QtWidgets.QFrame(uiGrid)
            frame_list.setMinimumSize(QtCore.QSize(685, 0))
            frame_list.setStyleSheet("border:none")
            frame_list.setFrameShape(QtWidgets.QFrame.StyledPanel)
            frame_list.setFrameShadow(QtWidgets.QFrame.Raised)
            frame_list.setObjectName("frame_list_{}".format(na + '_' + str(i)))
            self.frame_list.append(frame_list)
            
            horizontalLayout_list = QtWidgets.QHBoxLayout(self.frame_list[i])
            horizontalLayout_list.setContentsMargins(2, 0, 2, 0)
            horizontalLayout_list.setSpacing(10)
            horizontalLayout_list.setObjectName("horizontalLayout_{}".format(na + '_' + str(i)))
            self.horizontalLayout_list.append(horizontalLayout_list)
            
            self.add_pushButton(i, na, l)
            l = l + 4
            # print(l)
            self.verticalLayout_list_reco.addWidget(self.frame_list[i])
        self.retranslateUi(uiGrid, alt)
        
        QtCore.QMetaObject.connectSlotsByName(uiGrid)
    
    def add_pushButton(self, i, na, l):
        
        for x in range(4):
            splitter_list = QtWidgets.QSplitter(self.frame_list[i])
            splitter_list.setMinimumSize(QtCore.QSize(150, 200))
            splitter_list.setMaximumSize(QtCore.QSize(150, 200))
            splitter_list.setOrientation(Qt.Vertical)
            splitter_list.setObjectName("splitter_list_{}".format(na + '_' + str(l)))
            self.splitter_list.append(splitter_list)
            
            pushButton_list = QtWidgets.QPushButton(self.splitter_list[l])
            pushButton_list.setMinimumSize(QtCore.QSize(150, 150))
            pushButton_list.setMaximumSize(QtCore.QSize(150, 150))
            pushButton_list.setText("")
            icon = QtGui.QIcon()
            
            icon.addPixmap(QtGui.QPixmap("pachong/music/img/{}/{}.jpg".format(na,l)), QIcon.Normal, QIcon.Off)
            pushButton_list.setIcon(icon)
            pushButton_list.setIconSize(QtCore.QSize(150, 150))
            pushButton_list.setStyleSheet(
                    "border-radius:9px;padding-top:9px;"
            )
            pushButton_list.setAutoRepeat(True)
            pushButton_list.setObjectName("pushButton_list_{}".format(na + '_' + str(l)))
            self.pushButton_list.append(pushButton_list)
            
            label_list = QtWidgets.QLabel(self.splitter_list[l])
            label_list.setMinimumSize(QtCore.QSize(0, 40))
            label_list.setMaximumSize(QtCore.QSize(16777215, 40))
            label_list.setLayoutDirection(Qt.LeftToRight)
            label_list.setFrameShape(QtWidgets.QFrame.NoFrame)
            label_list.setFrameShadow(QtWidgets.QFrame.Plain)
            label_list.setStyleSheet('font: 8pt "本墨字语";')
            label_list.setLineWidth(0)
            label_list.setAlignment(Qt.AlignLeading | Qt.AlignLeft | Qt.AlignTop)
            label_list.setWordWrap(True)  # 自动换行
            label_list.setOpenExternalLinks(False)
            label_list.setObjectName("label_list_{}".format(na + '_' + str(l)))
            self.label_list.append(label_list)
            
            self.horizontalLayout_list[i].addWidget(self.splitter_list[l])
            # print(l)
            l = l + 1
    
    def retranslateUi(self, uiGrid, alt):
        _translate = QtCore.QCoreApplication.translate
        uiGrid.setWindowTitle(_translate("uiGrid", "QWidget"))
        # fi_na = r'C:\编程项目\软件项目\pachong\music\mc_reco'
        # group = 'alt'
        # alt = red_js(fi_na, group)
        a = 0
        for s in self.label_list:
            s.setText(_translate("uiGrid", alt[a]))
            a = a + 1
