# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ing_mc_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ing_mc(object):
    def setupUi(self, ing_mc):
        ing_mc.setObjectName("ing_mc")
        ing_mc.resize(322, 545)
        ing_mc.setMinimumSize(QtCore.QSize(0, 0))
        ing_mc.setMaximumSize(QtCore.QSize(16777215, 16777215))
        ing_mc.setStyleSheet(
            "QScrollArea{border:none;background-color:transparent;}\n"
            "QScrollArea QScrollBar:vertical{width:8px;\n"
            "background:transparent;margin:0px,1px,0px,1px;\n"
            "padding-top:0px;padding-bottom:0px;border-radius:2px;}\n"
            "QScrollArea QScrollBar::handle:vertical{\n"
            "border-radius:4px;\n"
            "    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(237, 180, 255, 200), stop:1 rgba(175, 211, 255, 200));\n"
            "}\n"
            "\n"
            "\n"
            "QScrollArea QScrollBar::handle:vertical:hover{border-radius:4px;\n"
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(237, 180, 255, 200), stop:1 rgba(175, 211, 255, 200));}\n"
            "\n"
            "QScrollArea QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical{\n"
            "background:transparent;border-radius:4px;}\n"
            "QScrollArea QScrollBar::add-line:vertical,QScrollBar::sub-line:vertical{\n"
            "height:0px;width:0px;}\n"
            )
        self.verticalLayout = QtWidgets.QVBoxLayout(ing_mc)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_ing_mc = QtWidgets.QFrame(ing_mc)
        self.frame_ing_mc.setMinimumSize(QtCore.QSize(302, 0))
        self.frame_ing_mc.setMaximumSize(QtCore.QSize(302, 16777215))
        self.frame_ing_mc.setStyleSheet(
            "#frame_ing_mc{border:0;background-color: rgb(255, 255, 255);border-bottom-right-radius:20px;border-bottom-left-radius:20px;border-top-right-radius:20px;border-top-left-radius:20px;}"
            )
        self.frame_ing_mc.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ing_mc.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ing_mc.setObjectName("frame_ing_mc")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_ing_mc)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_ing_mc_top = QtWidgets.QFrame(self.frame_ing_mc)
        self.frame_ing_mc_top.setMinimumSize(QtCore.QSize(302, 120))
        self.frame_ing_mc_top.setMaximumSize(QtCore.QSize(302, 120))
        self.frame_ing_mc_top.setStyleSheet(
            "#frame_ing_mc_top{;\n"
            "    background-color: rgb(255, 255, 255);\n"
            "border-top-right-radius:20px;\n"
            "    border-top-left-radius:20px;}"
            )
        self.frame_ing_mc_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ing_mc_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ing_mc_top.setObjectName("frame_ing_mc_top")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_ing_mc_top)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_ing_mc_top_collection = QtWidgets.QLabel(self.frame_ing_mc_top)
        font = QtGui.QFont()
        font.setFamily("本墨字语")
        font.setPointSize(15)
        self.label_ing_mc_top_collection.setFont(font)
        self.label_ing_mc_top_collection.setObjectName("label_ing_mc_top_collection")
        self.verticalLayout_2.addWidget(self.label_ing_mc_top_collection)
        self.label_ing_mc_top_collection_num = QtWidgets.QLabel(self.frame_ing_mc_top)
        font = QtGui.QFont()
        font.setFamily("本墨字语")
        font.setPointSize(9)
        self.label_ing_mc_top_collection_num.setFont(font)
        self.label_ing_mc_top_collection_num.setStyleSheet(
            "color: rgb(124, 124, 124);\n"
            "padding-left:8px;"
            )
        self.label_ing_mc_top_collection_num.setObjectName("label_ing_mc_top_collection_num")
        self.verticalLayout_2.addWidget(self.label_ing_mc_top_collection_num)
        self.frame__ing_mc_top = QtWidgets.QFrame(self.frame_ing_mc_top)
        self.frame__ing_mc_top.setMinimumSize(QtCore.QSize(0, 41))
        self.frame__ing_mc_top.setMaximumSize(QtCore.QSize(16777215, 41))
        self.frame__ing_mc_top.setStyleSheet(
            "QPushButton{\n"
            "    border:none;\n"
            "    color:rgb(81, 81, 81);\n"
            "}\n"
            "QPushButton:hover{  \n"
            "    padding-bottom:4px; \n"
            "    color: rgb(213, 8, 8);\n"
            "}\n"
            "QPushButton:focus {\n"
            "      color:rgb(255, 192, 2);\n"
            "      outline: 0px;\n"
            "    }"
            )
        self.frame__ing_mc_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame__ing_mc_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame__ing_mc_top.setObjectName("frame__ing_mc_top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame__ing_mc_top)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_ing_mc_top_collection = QtWidgets.QPushButton(self.frame__ing_mc_top)
        self.pushButton_ing_mc_top_collection.setMinimumSize(QtCore.QSize(80, 21))
        self.pushButton_ing_mc_top_collection.setMaximumSize(QtCore.QSize(80, 21))
        font = QtGui.QFont()
        font.setFamily("本墨字语")
        font.setPointSize(9)
        self.pushButton_ing_mc_top_collection.setFont(font)
        self.pushButton_ing_mc_top_collection.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 174, 254, 255), stop:1 rgba(149, 209, 214, 255));"
            "color: rgb(255, 255, 255);\n"
            "border-radius:8px;\n"
            "border: 1px solid  rgb(53, 53, 53);  "
            )
        self.pushButton_ing_mc_top_collection.setObjectName("pushButton_ing_mc_top_collection")
        self.horizontalLayout.addWidget(self.pushButton_ing_mc_top_collection)
        self.pushButton_ing_mc_top_clear = QtWidgets.QPushButton(self.frame__ing_mc_top)
        self.pushButton_ing_mc_top_clear.setMinimumSize(QtCore.QSize(80, 21))
        self.pushButton_ing_mc_top_clear.setMaximumSize(QtCore.QSize(80, 21))
        font = QtGui.QFont()
        font.setFamily("本墨字语")
        font.setPointSize(9)
        self.pushButton_ing_mc_top_clear.setFont(font)
        self.pushButton_ing_mc_top_clear.setStyleSheet(
            "border-radius:8px;\n"
            "border: 1px solid  rgb(53, 53, 53);  "
            )
        self.pushButton_ing_mc_top_clear.setObjectName("pushButton_ing_mc_top_clear")
        self.horizontalLayout.addWidget(self.pushButton_ing_mc_top_clear)
        self.verticalLayout_2.addWidget(self.frame__ing_mc_top)
        self.verticalLayout_5.addWidget(self.frame_ing_mc_top)
        self.frame_ing_mc_list = QtWidgets.QFrame(self.frame_ing_mc)
        self.frame_ing_mc_list.setStyleSheet(
            "#frame_ing_mc_list\n"
            "{border:0;\n"
            "border-bottom-right-radius:20px;\n"
            "    border-bottom-left-radius:20px;}"
            )
        self.frame_ing_mc_list.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ing_mc_list.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ing_mc_list.setObjectName("frame_ing_mc_list")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_ing_mc_list)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_ing_mc = QtWidgets.QScrollArea(self.frame_ing_mc_list)
        self.scrollArea_ing_mc.setMinimumSize(QtCore.QSize(300, 0))
        self.scrollArea_ing_mc.setMaximumSize(QtCore.QSize(300, 16777215))
        self.scrollArea_ing_mc.setStyleSheet(
            "#scrollArea_ing_mc\n"
            "{border:0;"
            "border-bottom-right-radius:20px;\n"
            "    border-bottom-left-radius:20px;}"
            )
        self.scrollArea_ing_mc.setLineWidth(1)
        self.scrollArea_ing_mc.setWidgetResizable(True)
        self.scrollArea_ing_mc.setObjectName("scrollArea_ing_mc")
        self.scrollAreaWidgetContents_ing_mc = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_ing_mc.setGeometry(QtCore.QRect(0, 0, 300, 405))
        self.scrollAreaWidgetContents_ing_mc.setStyleSheet("")
        self.scrollAreaWidgetContents_ing_mc.setObjectName("scrollAreaWidgetContents_ing_mc")
        self.verticalLayout_ing_mc_so = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_ing_mc)
        self.verticalLayout_ing_mc_so.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_ing_mc_so.setSpacing(0)
        self.verticalLayout_ing_mc_so.setObjectName("verticalLayout_ing_mc_so")

        spacerItem1 = QtWidgets.QSpacerItem(20, 338, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_ing_mc_so.addItem(spacerItem1)
        self.scrollArea_ing_mc.setWidget(self.scrollAreaWidgetContents_ing_mc)
        self.verticalLayout_3.addWidget(self.scrollArea_ing_mc, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addWidget(self.frame_ing_mc_list)
        self.verticalLayout.addWidget(self.frame_ing_mc)
        
        self.retranslateUi(ing_mc)
        QtCore.QMetaObject.connectSlotsByName(ing_mc)


    def retranslateUi(self, ing_mc):
        _translate = QtCore.QCoreApplication.translate
        ing_mc.setWindowTitle(_translate("ing_mc", "Form"))
        self.label_ing_mc_top_collection.setText(_translate("ing_mc", "当前播放"))
        self.label_ing_mc_top_collection_num.setText(_translate("ing_mc", "总{}首"))
        self.pushButton_ing_mc_top_collection.setText(_translate("ing_mc", "全部收藏"))
        self.pushButton_ing_mc_top_clear.setText(_translate("ing_mc", "清空列表"))
        


