# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frame_ing_mc_so_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget


class Ui_li(QWidget):
    def __init__(self, so_na, so_ti):
        super(Ui_li, self).__init__()
        
        self.setupUi(self, so_na, so_ti)
    
    def setupUi(self, li, so_na, so_ti):
        li.setObjectName("li")
        li.resize(290, 35)
        li.setStyleSheet(
                "QPushButton{border:0;\n"
                "font: 8pt \"本墨字语\";\n"
                "background-color: rgba(255, 255, 255, 255);}\n"
                "QPushButton:hover{  \n"
                "    padding-bottom:2px; \n"
                "color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 174, 254, 255), stop:1 rgba(70, 181, 214, 255));}\n "
                "QLabel{background-color: rgba(255, 255, 255, 255);\n"
                "font: 8pt \"本墨字语\";\n"
                "}\n"
                "QFrame{background-color: rgba(255, 255, 255, 255);}"
        )
        self.verticalLayout_ing_mc_so_li = QtWidgets.QVBoxLayout(li)
        self.verticalLayout_ing_mc_so_li.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_ing_mc_so_li.setSpacing(0)
        self.verticalLayout_ing_mc_so_li.setObjectName("verticalLayout_ing_mc_so_li_{}".format(so_na))
        self.frame_ing_mc_so = QtWidgets.QFrame(li)
        self.frame_ing_mc_so.setMinimumSize(QtCore.QSize(290, 35))
        self.frame_ing_mc_so.setMaximumSize(QtCore.QSize(290, 35))
        self.frame_ing_mc_so.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ing_mc_so.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ing_mc_so.setObjectName("frame_ing_mc_so_{}".format(so_na))
        
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_ing_mc_so)
        self.horizontalLayout.setContentsMargins(9, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout_{}".format(so_na))
        
        self.pushButton_ing_mc_so_name = QtWidgets.QPushButton(self.frame_ing_mc_so)
        self.pushButton_ing_mc_so_name.setMinimumSize(QtCore.QSize(235, 35))
        self.pushButton_ing_mc_so_name.setMaximumSize(QtCore.QSize(235, 35))
        font = QtGui.QFont()
        font.setFamily("本墨字语")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_ing_mc_so_name.setFont(font)
        self.pushButton_ing_mc_so_name.setStyleSheet("text-align :left;")
        self.pushButton_ing_mc_so_name.setObjectName("pushButton_ing_mc_so_name_{}".format(so_na))
        # print("pushButton_ing_mc_so_name_{}".format(so_na))
        self.horizontalLayout.addWidget(self.pushButton_ing_mc_so_name)
        
        self.label_ing_mc_so_time = QtWidgets.QLabel(self.frame_ing_mc_so)
        self.label_ing_mc_so_time.setMinimumSize(QtCore.QSize(45, 35))
        self.label_ing_mc_so_time.setMaximumSize(QtCore.QSize(45, 35))
        font = QtGui.QFont()
        font.setFamily("本墨字语")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_ing_mc_so_time.setFont(font)
        self.label_ing_mc_so_time.setObjectName("label_ing_mc_so_time_{}".format(so_na))
        self.horizontalLayout.addWidget(self.label_ing_mc_so_time)
        self.verticalLayout_ing_mc_so_li.addWidget(self.frame_ing_mc_so)
        
        self.retranslateUi(li, so_na, so_ti)
        QtCore.QMetaObject.connectSlotsByName(li)
    
    def retranslateUi(self, li, so_na, so_ti):
        _translate = QtCore.QCoreApplication.translate
        li.setWindowTitle(_translate("li", "li"))
        self.pushButton_ing_mc_so_name.setText(_translate("ing_mc", so_na))
        self.pushButton_ing_mc_so_name.setToolTip(
                _translate(
                        "ranking_list",
                        "<html><head/><body><p><span style=\" font-size:8pt; font-family:\'本墨字语\'\">{}</span></p></body></html>".format(
                                so_na
                        )
                )
        )
        self.label_ing_mc_so_time.setText(_translate("ing_mc", str(so_ti)))
