# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ranking_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget

from ui.tooltip.demo import ToolTip

background = 'background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 174, 254, 255),' \
             'stop:1 rgba(149, 209, 214, 255)) '
style = 'background-color:rgb(247, 248, 255)'
style2 = 'background-color:rgb(237, 238, 255)'


class Ui_local_mc_list(QWidget):
    def __init__(self, num, na, so_ti):
        super(Ui_local_mc_list, self).__init__()
        
        self.setupUi(self, num, na, so_ti)
    
    def setupUi(self, local_mc_list, num, na, so_ti):
        if num%2 == 0:
            sty = style2
        else:
            sty = style
        local_mc_list.setObjectName("local_mc_list")
        # local_mc_list.resize(830, 40)
        self.verticalLayout = QtWidgets.QVBoxLayout(local_mc_list)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mc_local_list_1 = QtWidgets.QFrame(local_mc_list)
        self.mc_local_list_1.setMinimumSize(QtCore.QSize(0, 40))
        self.mc_local_list_1.setMaximumSize(QtCore.QSize(16777215, 40))
        self.mc_local_list_1.setStyleSheet(
                "QFrame,QLabel,QPushButton,QRadioButton{border:none;%s}QPushButton:hover{color: qlineargradient("
                "spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(162, 179, 255, 255), stop:1 rgba(144, 228, 137, "
                "255));}" % sty
        )
        self.mc_local_list_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mc_local_list_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mc_local_list_1.setObjectName("mc_local_list_1")
        self.horizontalLayout_frame_song_list_bottom_inf = QtWidgets.QHBoxLayout(self.mc_local_list_1)
        self.horizontalLayout_frame_song_list_bottom_inf.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_frame_song_list_bottom_inf.setSpacing(0)
        self.horizontalLayout_frame_song_list_bottom_inf.setObjectName("horizontalLayout_frame_song_list_bottom_inf")
        self.mc_local_list_1_no = QtWidgets.QLabel(self.mc_local_list_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mc_local_list_1_no.sizePolicy().hasHeightForWidth())
        self.mc_local_list_1_no.setSizePolicy(sizePolicy)
        self.mc_local_list_1_no.setMinimumSize(QtCore.QSize(40, 40))
        self.mc_local_list_1_no.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("本墨字语")
        font.setPointSize(9)
        self.mc_local_list_1_no.setFont(font)
        self.mc_local_list_1_no.setStyleSheet("")
        self.mc_local_list_1_no.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_local_list_1_no.setObjectName("mc_local_list_1_no")
        self.horizontalLayout_frame_song_list_bottom_inf.addWidget(self.mc_local_list_1_no)
        self.mc_local_list_1_name = QtWidgets.QPushButton(self.mc_local_list_1)
        self.mc_local_list_1_name.setMinimumSize(QtCore.QSize(540, 40))
        self.mc_local_list_1_name.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("本墨字语")
        font.setPointSize(10)
        self.mc_local_list_1_name.setFont(font)
        self.mc_local_list_1_name.setStyleSheet("text-align :left;")
        self.mc_local_list_1_name.setObjectName("mc_local_list_1_name")
        self.horizontalLayout_frame_song_list_bottom_inf.addWidget(self.mc_local_list_1_name)
        self.mc_local_list_1_ti = QtWidgets.QLabel(self.mc_local_list_1)
        self.mc_local_list_1_ti.setMinimumSize(QtCore.QSize(40, 40))
        self.mc_local_list_1_ti.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("本墨字语")
        font.setPointSize(9)
        self.mc_local_list_1_ti.setFont(font)
        self.mc_local_list_1_ti.setObjectName("mc_local_list_1_ti")
        self.horizontalLayout_frame_song_list_bottom_inf.addWidget(self.mc_local_list_1_ti)
        self.mc_local_list_1_play = QtWidgets.QPushButton(self.mc_local_list_1)
        self.mc_local_list_1_play.setMinimumSize(QtCore.QSize(190, 40))
        self.mc_local_list_1_play.setMaximumSize(QtCore.QSize(190, 40))
        self.mc_local_list_1_play.setText("")
        self.mc_local_list_1_play.setIcon(QtGui.QIcon(":/icon/icon/play.png"))
        self.mc_local_list_1_play.setIconSize(QtCore.QSize(15, 15))
        self.mc_local_list_1_play.setObjectName("mc_local_list_1_play")
        self.horizontalLayout_frame_song_list_bottom_inf.addWidget(self.mc_local_list_1_play)
        self.verticalLayout.addWidget(self.mc_local_list_1)
        
        self.retranslateUi(local_mc_list,num, na, so_ti)
        QtCore.QMetaObject.connectSlotsByName(local_mc_list)
    
    def retranslateUi(self, local_mc_list, num, na, so_ti):
        _translate = QtCore.QCoreApplication.translate
        local_mc_list.setWindowTitle(_translate("local_mc_list", "Form"))
        self.mc_local_list_1_no.setText(_translate("local_mc_list", str(num)))
        self.mc_local_list_1_name.setText(_translate("local_mc_list", na))
        self.mc_local_list_1_ti.setText(_translate("local_mc_list", so_ti))



import pic.icon_rc
