# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'song_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_song_list(object):
    def setupUi(self, song_list):
        song_list.setObjectName("song_list")
        song_list.resize(700, 360)
        song_list.setMinimumSize(QtCore.QSize(700, 0))
        song_list.setMaximumSize(QtCore.QSize(700, 16777215))
        song_list.setStyleSheet("\n"
"\n"
"QFrame{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{  \n"
"    padding-bottom:2px; \n"
"}\n"
"\n"
"")
        self.verticalLayout_song_list = QtWidgets.QVBoxLayout(song_list)
        self.verticalLayout_song_list.setContentsMargins(0, 20, 0, 0)
        self.verticalLayout_song_list.setSpacing(0)
        self.verticalLayout_song_list.setObjectName("verticalLayout_song_list")
        self.song_list_top = QtWidgets.QFrame(song_list)
        self.song_list_top.setMaximumSize(QtCore.QSize(16777215, 220))
        self.song_list_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.song_list_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.song_list_top.setObjectName("song_list_top")
        self.horizontalLayout_song_list_bottom = QtWidgets.QHBoxLayout(self.song_list_top)
        self.horizontalLayout_song_list_bottom.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_song_list_bottom.setSpacing(0)
        self.horizontalLayout_song_list_bottom.setObjectName("horizontalLayout_song_list_bottom")
        self.frame_song_list_top_logo = QtWidgets.QFrame(self.song_list_top)
        self.frame_song_list_top_logo.setMinimumSize(QtCore.QSize(220, 220))
        self.frame_song_list_top_logo.setMaximumSize(QtCore.QSize(220, 220))
        self.frame_song_list_top_logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_song_list_top_logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_song_list_top_logo.setObjectName("frame_song_list_top_logo")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_song_list_top_logo)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_song_list_top_logo = QtWidgets.QPushButton(self.frame_song_list_top_logo)
        self.pushButton_song_list_top_logo.setMinimumSize(QtCore.QSize(200, 200))
        self.pushButton_song_list_top_logo.setMaximumSize(QtCore.QSize(200, 200))
        self.pushButton_song_list_top_logo.setStyleSheet("border-image: url(:/image/image/2.png);")
        self.pushButton_song_list_top_logo.setText("")
        self.pushButton_song_list_top_logo.setObjectName("pushButton_song_list_top_logo")
        self.verticalLayout_3.addWidget(self.pushButton_song_list_top_logo, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_song_list_bottom.addWidget(self.frame_song_list_top_logo)
        self.frame_list_top_right = QtWidgets.QFrame(self.song_list_top)
        self.frame_list_top_right.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    border-radius:8px;\n"
"    background-color: rgb(227, 227, 227);\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 128, 0);\n"
"    \n"
"}\n"
"")
        self.frame_list_top_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_list_top_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_list_top_right.setObjectName("frame_list_top_right")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_list_top_right)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_list_top_right_title = QtWidgets.QFrame(self.frame_list_top_right)
        self.frame_list_top_right_title.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_list_top_right_title.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_list_top_right_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_list_top_right_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_list_top_right_title.setObjectName("frame_list_top_right_title")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_list_top_right_title)
        self.horizontalLayout_3.setContentsMargins(15, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_song_list_top_title = QtWidgets.QLabel(self.frame_list_top_right_title)
        self.label_song_list_top_title.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("本墨字语")
        font.setPointSize(12)
        self.label_song_list_top_title.setFont(font)
        self.label_song_list_top_title.setObjectName("label_song_list_top_title")
        self.horizontalLayout_3.addWidget(self.label_song_list_top_title)
        self.verticalLayout_2.addWidget(self.frame_list_top_right_title)
        self.frame_list_top_right_mid = QtWidgets.QFrame(self.frame_list_top_right)
        self.frame_list_top_right_mid.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_list_top_right_mid.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_list_top_right_mid.setStyleSheet("QPushButton{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font: 10pt \"本墨字语\";\n"
"}\n"
"QPushButton:hover{  \n"
"    \n"
"    color: rgb(213, 8, 8);\n"
"    padding-bottom:3px; \n"
"}\n"
"QPushButton:focus {\n"
"      color: rgb(255, 255, 255);\n"
"      outline: 0px;\n"
"    }\n"
"QPushButton:pressed{\n"
"    background-color: rgb(200, 200, 200);\n"
"    color: rgb(255, 149, 0);\n"
"}\n"
"")
        self.frame_list_top_right_mid.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_list_top_right_mid.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_list_top_right_mid.setObjectName("frame_list_top_right_mid")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_list_top_right_mid)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_song_list_top_play = QtWidgets.QPushButton(self.frame_list_top_right_mid)
        self.pushButton_song_list_top_play.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_song_list_top_play.setMaximumSize(QtCore.QSize(140, 30))
        self.pushButton_song_list_top_play.setStyleSheet("border: 1px solid  rgb(53, 53, 53);  ")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_song_list_top_play.setIcon(icon)
        self.pushButton_song_list_top_play.setIconSize(QtCore.QSize(12, 12))
        self.pushButton_song_list_top_play.setObjectName("pushButton_song_list_top_play")
        self.horizontalLayout_4.addWidget(self.pushButton_song_list_top_play)
        self.pushButton_song_list_top_collect = QtWidgets.QPushButton(self.frame_list_top_right_mid)
        self.pushButton_song_list_top_collect.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_song_list_top_collect.setMaximumSize(QtCore.QSize(140, 30))
        self.pushButton_song_list_top_collect.setStyleSheet("border: 1px solid  rgb(53, 53, 53);  ")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/add_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_song_list_top_collect.setIcon(icon1)
        self.pushButton_song_list_top_collect.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_song_list_top_collect.setObjectName("pushButton_song_list_top_collect")
        self.horizontalLayout_4.addWidget(self.pushButton_song_list_top_collect)
        self.pushButton_song_list_top_load = QtWidgets.QPushButton(self.frame_list_top_right_mid)
        self.pushButton_song_list_top_load.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_song_list_top_load.setMaximumSize(QtCore.QSize(140, 30))
        self.pushButton_song_list_top_load.setStyleSheet("border: 1px solid  rgb(53, 53, 53);  ")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_song_list_top_load.setIcon(icon2)
        self.pushButton_song_list_top_load.setObjectName("pushButton_song_list_top_load")
        self.horizontalLayout_4.addWidget(self.pushButton_song_list_top_load)
        self.verticalLayout_2.addWidget(self.frame_list_top_right_mid)
        self.frame_list_top_right_bottom = QtWidgets.QFrame(self.frame_list_top_right)
        self.frame_list_top_right_bottom.setStyleSheet("font: 8pt \"本墨字语\";")
        self.frame_list_top_right_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_list_top_right_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_list_top_right_bottom.setObjectName("frame_list_top_right_bottom")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_list_top_right_bottom)
        self.horizontalLayout_2.setContentsMargins(6, 6, 6, 4)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_song_list_top_inf = QtWidgets.QFrame(self.frame_list_top_right_bottom)
        self.frame_song_list_top_inf.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_song_list_top_inf.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_song_list_top_inf.setObjectName("frame_song_list_top_inf")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_song_list_top_inf)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_song_list_top_inf)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 468, 130))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_song_list_top_inf = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_song_list_top_inf.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_song_list_top_inf.setObjectName("label_song_list_top_inf")
        self.verticalLayout_4.addWidget(self.label_song_list_top_inf)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_2.addWidget(self.frame_song_list_top_inf)
        self.verticalLayout_2.addWidget(self.frame_list_top_right_bottom)
        self.horizontalLayout_song_list_bottom.addWidget(self.frame_list_top_right)
        self.verticalLayout_song_list.addWidget(self.song_list_top)
        self.song_list_bottom = QtWidgets.QFrame(song_list)
        self.song_list_bottom.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    color:rgb(98, 98, 98);\n"
"    text-align :center;\n"
"    font: 9pt \"本墨字语\";\n"
"}\n"
"QPushButton:hover{  \n"
"    padding-bottom:4px; \n"
"}\n"
"QPushButton:focus {\n"
"      color: rgb(255, 192, 2);;\n"
"      outline: 0px;\n"
"    }\n"
"QLabel{\n"
"    font: 9pt \"本墨字语\";\n"
"}")
        self.song_list_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.song_list_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.song_list_bottom.setObjectName("song_list_bottom")
        self.verticalLayout_song_list_bottom = QtWidgets.QVBoxLayout(self.song_list_bottom)
        self.verticalLayout_song_list_bottom.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_song_list_bottom.setSpacing(0)
        self.verticalLayout_song_list_bottom.setObjectName("verticalLayout_song_list_bottom")
        self.frame_song_list_list_bottom_lable = QtWidgets.QFrame(self.song_list_bottom)
        self.frame_song_list_list_bottom_lable.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_song_list_list_bottom_lable.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_song_list_list_bottom_lable.setStyleSheet("")
        self.frame_song_list_list_bottom_lable.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_song_list_list_bottom_lable.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_song_list_list_bottom_lable.setObjectName("frame_song_list_list_bottom_lable")
        self.horizontalLayout_frame_song_list_list_bottom_lable = QtWidgets.QHBoxLayout(self.frame_song_list_list_bottom_lable)
        self.horizontalLayout_frame_song_list_list_bottom_lable.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_frame_song_list_list_bottom_lable.setSpacing(0)
        self.horizontalLayout_frame_song_list_list_bottom_lable.setObjectName("horizontalLayout_frame_song_list_list_bottom_lable")
        self.label_song_list_list_top_no = QtWidgets.QLabel(self.frame_song_list_list_bottom_lable)
        self.label_song_list_list_top_no.setMinimumSize(QtCore.QSize(40, 40))
        self.label_song_list_list_top_no.setMaximumSize(QtCore.QSize(40, 40))
        self.label_song_list_list_top_no.setStyleSheet("")
        self.label_song_list_list_top_no.setAlignment(QtCore.Qt.AlignCenter)
        self.label_song_list_list_top_no.setObjectName("label_song_list_list_top_no")
        self.horizontalLayout_frame_song_list_list_bottom_lable.addWidget(self.label_song_list_list_top_no)
        self.pushButton_song_list_list_top_choice = QtWidgets.QPushButton(self.frame_song_list_list_bottom_lable)
        self.pushButton_song_list_list_top_choice.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_song_list_list_top_choice.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_song_list_list_top_choice.setText("")
        self.pushButton_song_list_list_top_choice.setObjectName("pushButton_song_list_list_top_choice")
        self.horizontalLayout_frame_song_list_list_bottom_lable.addWidget(self.pushButton_song_list_list_top_choice)
        self.pushButton_song_list_list_top_name = QtWidgets.QPushButton(self.frame_song_list_list_bottom_lable)
        self.pushButton_song_list_list_top_name.setMinimumSize(QtCore.QSize(540, 40))
        self.pushButton_song_list_list_top_name.setMaximumSize(QtCore.QSize(540, 40))
        self.pushButton_song_list_list_top_name.setStyleSheet("text-align :left;")
        self.pushButton_song_list_list_top_name.setObjectName("pushButton_song_list_list_top_name")
        self.horizontalLayout_frame_song_list_list_bottom_lable.addWidget(self.pushButton_song_list_list_top_name)
        self.pushButton_song_list_list_top_play = QtWidgets.QPushButton(self.frame_song_list_list_bottom_lable)
        self.pushButton_song_list_list_top_play.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_song_list_list_top_play.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_song_list_list_top_play.setObjectName("pushButton_song_list_list_top_play")
        self.horizontalLayout_frame_song_list_list_bottom_lable.addWidget(self.pushButton_song_list_list_top_play)
        self.pushButton_song_list_list_top_download = QtWidgets.QPushButton(self.frame_song_list_list_bottom_lable)
        self.pushButton_song_list_list_top_download.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_song_list_list_top_download.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_song_list_list_top_download.setObjectName("pushButton_song_list_list_top_download")
        self.horizontalLayout_frame_song_list_list_bottom_lable.addWidget(self.pushButton_song_list_list_top_download)
        self.verticalLayout_song_list_bottom.addWidget(self.frame_song_list_list_bottom_lable)
        self.frame_song_list_bottom_inf = QtWidgets.QFrame(self.song_list_bottom)
        self.frame_song_list_bottom_inf.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_song_list_bottom_inf.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_song_list_bottom_inf.setStyleSheet("QPushButton:hover{  \n"
"    \n"
"    background-color: rgb(222, 222, 222);\n"
"}")
        self.frame_song_list_bottom_inf.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_song_list_bottom_inf.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_song_list_bottom_inf.setObjectName("frame_song_list_bottom_inf")
        self.horizontalLayout_frame_song_list_bottom_inf = QtWidgets.QHBoxLayout(self.frame_song_list_bottom_inf)
        self.horizontalLayout_frame_song_list_bottom_inf.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_frame_song_list_bottom_inf.setSpacing(0)
        self.horizontalLayout_frame_song_list_bottom_inf.setObjectName("horizontalLayout_frame_song_list_bottom_inf")
        self.label_song_list_bottom_no = QtWidgets.QLabel(self.frame_song_list_bottom_inf)
        self.label_song_list_bottom_no.setMinimumSize(QtCore.QSize(40, 40))
        self.label_song_list_bottom_no.setMaximumSize(QtCore.QSize(40, 40))
        self.label_song_list_bottom_no.setStyleSheet("")
        self.label_song_list_bottom_no.setAlignment(QtCore.Qt.AlignCenter)
        self.label_song_list_bottom_no.setObjectName("label_song_list_bottom_no")
        self.horizontalLayout_frame_song_list_bottom_inf.addWidget(self.label_song_list_bottom_no)
        self.radioButton_song_list_bottom_choice = QtWidgets.QRadioButton(self.frame_song_list_bottom_inf)
        self.radioButton_song_list_bottom_choice.setMinimumSize(QtCore.QSize(40, 40))
        self.radioButton_song_list_bottom_choice.setMaximumSize(QtCore.QSize(40, 40))
        self.radioButton_song_list_bottom_choice.setText("")
        self.radioButton_song_list_bottom_choice.setChecked(True)
        self.radioButton_song_list_bottom_choice.setObjectName("radioButton_song_list_bottom_choice")
        self.horizontalLayout_frame_song_list_bottom_inf.addWidget(self.radioButton_song_list_bottom_choice)
        self.pushButton_song_list_bottom_name = QtWidgets.QPushButton(self.frame_song_list_bottom_inf)
        self.pushButton_song_list_bottom_name.setMinimumSize(QtCore.QSize(540, 40))
        self.pushButton_song_list_bottom_name.setMaximumSize(QtCore.QSize(540, 40))
        self.pushButton_song_list_bottom_name.setStyleSheet("text-align :left;")
        self.pushButton_song_list_bottom_name.setObjectName("pushButton_song_list_bottom_name")
        self.horizontalLayout_frame_song_list_bottom_inf.addWidget(self.pushButton_song_list_bottom_name)
        self.pushButton_song_list_bottom_play = QtWidgets.QPushButton(self.frame_song_list_bottom_inf)
        self.pushButton_song_list_bottom_play.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_song_list_bottom_play.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_song_list_bottom_play.setText("")
        self.pushButton_song_list_bottom_play.setIcon(icon)
        self.pushButton_song_list_bottom_play.setIconSize(QtCore.QSize(13, 13))
        self.pushButton_song_list_bottom_play.setObjectName("pushButton_song_list_bottom_play")
        self.horizontalLayout_frame_song_list_bottom_inf.addWidget(self.pushButton_song_list_bottom_play)
        self.pushButton_song_list_bottom_download = QtWidgets.QPushButton(self.frame_song_list_bottom_inf)
        self.pushButton_song_list_bottom_download.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_song_list_bottom_download.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_song_list_bottom_download.setText("")
        self.pushButton_song_list_bottom_download.setIcon(icon2)
        self.pushButton_song_list_bottom_download.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_song_list_bottom_download.setObjectName("pushButton_song_list_bottom_download")
        self.horizontalLayout_frame_song_list_bottom_inf.addWidget(self.pushButton_song_list_bottom_download)
        self.verticalLayout_song_list_bottom.addWidget(self.frame_song_list_bottom_inf)
        self.frame_song_list_bottom_inf_2 = QtWidgets.QFrame(self.song_list_bottom)
        self.frame_song_list_bottom_inf_2.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_song_list_bottom_inf_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_song_list_bottom_inf_2.setStyleSheet("QPushButton:hover{  \n"
"    \n"
"    background-color: rgb(222, 222, 222);\n"
"}")
        self.frame_song_list_bottom_inf_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_song_list_bottom_inf_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_song_list_bottom_inf_2.setObjectName("frame_song_list_bottom_inf_2")
        self.horizontalLayout_frame_song_list_bottom_inf_2 = QtWidgets.QHBoxLayout(self.frame_song_list_bottom_inf_2)
        self.horizontalLayout_frame_song_list_bottom_inf_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_frame_song_list_bottom_inf_2.setSpacing(0)
        self.horizontalLayout_frame_song_list_bottom_inf_2.setObjectName("horizontalLayout_frame_song_list_bottom_inf_2")
        self.label_song_list_bottom_no_2 = QtWidgets.QLabel(self.frame_song_list_bottom_inf_2)
        self.label_song_list_bottom_no_2.setMinimumSize(QtCore.QSize(40, 40))
        self.label_song_list_bottom_no_2.setMaximumSize(QtCore.QSize(40, 40))
        self.label_song_list_bottom_no_2.setStyleSheet("")
        self.label_song_list_bottom_no_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_song_list_bottom_no_2.setObjectName("label_song_list_bottom_no_2")
        self.horizontalLayout_frame_song_list_bottom_inf_2.addWidget(self.label_song_list_bottom_no_2)
        self.radioButton_song_list_bottom_choice_2 = QtWidgets.QRadioButton(self.frame_song_list_bottom_inf_2)
        self.radioButton_song_list_bottom_choice_2.setMinimumSize(QtCore.QSize(40, 40))
        self.radioButton_song_list_bottom_choice_2.setMaximumSize(QtCore.QSize(40, 40))
        self.radioButton_song_list_bottom_choice_2.setText("")
        self.radioButton_song_list_bottom_choice_2.setChecked(True)
        self.radioButton_song_list_bottom_choice_2.setObjectName("radioButton_song_list_bottom_choice_2")
        self.horizontalLayout_frame_song_list_bottom_inf_2.addWidget(self.radioButton_song_list_bottom_choice_2)
        self.pushButton_song_list_bottom_name_2 = QtWidgets.QPushButton(self.frame_song_list_bottom_inf_2)
        self.pushButton_song_list_bottom_name_2.setMinimumSize(QtCore.QSize(540, 40))
        self.pushButton_song_list_bottom_name_2.setMaximumSize(QtCore.QSize(540, 40))
        self.pushButton_song_list_bottom_name_2.setStyleSheet("text-align :left;")
        self.pushButton_song_list_bottom_name_2.setObjectName("pushButton_song_list_bottom_name_2")
        self.horizontalLayout_frame_song_list_bottom_inf_2.addWidget(self.pushButton_song_list_bottom_name_2)
        self.pushButton_song_list_bottom_play_2 = QtWidgets.QPushButton(self.frame_song_list_bottom_inf_2)
        self.pushButton_song_list_bottom_play_2.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_song_list_bottom_play_2.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_song_list_bottom_play_2.setText("")
        self.pushButton_song_list_bottom_play_2.setIcon(icon)
        self.pushButton_song_list_bottom_play_2.setIconSize(QtCore.QSize(13, 13))
        self.pushButton_song_list_bottom_play_2.setObjectName("pushButton_song_list_bottom_play_2")
        self.horizontalLayout_frame_song_list_bottom_inf_2.addWidget(self.pushButton_song_list_bottom_play_2)
        self.pushButton_song_list_bottom_download_2 = QtWidgets.QPushButton(self.frame_song_list_bottom_inf_2)
        self.pushButton_song_list_bottom_download_2.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_song_list_bottom_download_2.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_song_list_bottom_download_2.setText("")
        self.pushButton_song_list_bottom_download_2.setIcon(icon2)
        self.pushButton_song_list_bottom_download_2.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_song_list_bottom_download_2.setObjectName("pushButton_song_list_bottom_download_2")
        self.horizontalLayout_frame_song_list_bottom_inf_2.addWidget(self.pushButton_song_list_bottom_download_2)
        self.verticalLayout_song_list_bottom.addWidget(self.frame_song_list_bottom_inf_2)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_song_list_bottom.addItem(spacerItem)
        self.verticalLayout_song_list.addWidget(self.song_list_bottom)

        self.retranslateUi(song_list)
        self.pushButton_song_list_bottom_name.clicked.connect(self.radioButton_song_list_bottom_choice.click)
        self.pushButton_song_list_bottom_name_2.clicked.connect(self.radioButton_song_list_bottom_choice_2.click)
        QtCore.QMetaObject.connectSlotsByName(song_list)

    def retranslateUi(self, song_list):
        _translate = QtCore.QCoreApplication.translate
        song_list.setWindowTitle(_translate("song_list", "Form"))
        self.label_song_list_top_title.setText(_translate("song_list", "TextLabel"))
        self.pushButton_song_list_top_play.setText(_translate("song_list", "播放列表"))
        self.pushButton_song_list_top_collect.setText(_translate("song_list", "收藏歌单"))
        self.pushButton_song_list_top_load.setText(_translate("song_list", "下载列表"))
        self.label_song_list_top_inf.setText(_translate("song_list", "TextLabel"))
        self.label_song_list_list_top_no.setText(_translate("song_list", "序号"))
        self.pushButton_song_list_list_top_name.setText(_translate("song_list", "歌曲"))
        self.pushButton_song_list_list_top_play.setText(_translate("song_list", "播放"))
        self.pushButton_song_list_list_top_download.setText(_translate("song_list", "下载"))
        self.label_song_list_bottom_no.setText(_translate("song_list", "1"))
        self.pushButton_song_list_bottom_name.setText(_translate("song_list", "发发发发发发付付付付付付"))
        self.label_song_list_bottom_no_2.setText(_translate("song_list", "2"))
        self.pushButton_song_list_bottom_name_2.setText(_translate("song_list", "asdddddddddddddddddddddddddddddddddddddddddddddddddddddddd"))
import icon_rc
