# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ranking_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ranking_list(object):
    def setupUi(self, ranking_list):
        ranking_list.setObjectName("ranking_list")
        ranking_list.resize(888, 246)
        ranking_list.setMinimumSize(QtCore.QSize(888, 0))
        ranking_list.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"QToolTip{border:0;background-color: rgb(94, 94, 94);}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(ranking_list)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ranking_list_Top = QtWidgets.QFrame(ranking_list)
        self.ranking_list_Top.setMinimumSize(QtCore.QSize(700, 100))
        self.ranking_list_Top.setMaximumSize(QtCore.QSize(16777215, 100))
        self.ranking_list_Top.setToolTipDuration(14)
        self.ranking_list_Top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ranking_list_Top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ranking_list_Top.setObjectName("ranking_list_Top")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ranking_list_Top)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ranking_list_Top_na_Label = QtWidgets.QLabel(self.ranking_list_Top)
        self.ranking_list_Top_na_Label.setMinimumSize(QtCore.QSize(300, 80))
        self.ranking_list_Top_na_Label.setMaximumSize(QtCore.QSize(300, 80))
        font = QtGui.QFont()
        font.setFamily("二字元风波泡泡简")
        font.setPointSize(50)
        font.setBold(False)
        font.setWeight(50)
        self.ranking_list_Top_na_Label.setFont(font)
        self.ranking_list_Top_na_Label.setStyleSheet("padding-top:10px;\n"
"padding-right:50px;\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(223, 125, 255, 255), stop:1 rgba(130, 186, 255, 255));")
        self.ranking_list_Top_na_Label.setObjectName("ranking_list_Top_na_Label")
        self.verticalLayout_2.addWidget(self.ranking_list_Top_na_Label)
        self.verticalLayout.addWidget(self.ranking_list_Top)
        self.ranking_list_Bottom = QtWidgets.QFrame(ranking_list)
        self.ranking_list_Bottom.setStyleSheet("#song_list_bottom{border: 1px solid  qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(247, 141, 147, 255), stop:0.965909 rgba(141, 193, 255, 255))}\n"
"QPushButton{\n"
"    border:none;\n"
"    color:rgb(98, 98, 98);\n"
"    text-align :center;\n"
"    font: 9pt \"本墨字语\";\n"
"}\n"
"QPushButton:hover{  \n"
"    padding-bottom:2px; \n"
"}\n"
"QLabel{\n"
"    font: 9pt \"本墨字语\";\n"
"}")
        self.ranking_list_Bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ranking_list_Bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ranking_list_Bottom.setObjectName("ranking_list_Bottom")
        self.verticalLayout_song_list_bottom = QtWidgets.QVBoxLayout(self.ranking_list_Bottom)
        self.verticalLayout_song_list_bottom.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_song_list_bottom.setSpacing(0)
        self.verticalLayout_song_list_bottom.setObjectName("verticalLayout_song_list_bottom")
        self.ranking_list_Bottom_td_0 = QtWidgets.QFrame(self.ranking_list_Bottom)
        self.ranking_list_Bottom_td_0.setMinimumSize(QtCore.QSize(0, 40))
        self.ranking_list_Bottom_td_0.setMaximumSize(QtCore.QSize(16777215, 40))
        self.ranking_list_Bottom_td_0.setStyleSheet("")
        self.ranking_list_Bottom_td_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ranking_list_Bottom_td_0.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ranking_list_Bottom_td_0.setObjectName("ranking_list_Bottom_td_0")
        self.horizontalLayout_frame_song_list_list_bottom_lable = QtWidgets.QHBoxLayout(self.ranking_list_Bottom_td_0)
        self.horizontalLayout_frame_song_list_list_bottom_lable.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_frame_song_list_list_bottom_lable.setSpacing(0)
        self.horizontalLayout_frame_song_list_list_bottom_lable.setObjectName("horizontalLayout_frame_song_list_list_bottom_lable")
        self.ranking_list_Bottom_td_0_xuhao = QtWidgets.QLabel(self.ranking_list_Bottom_td_0)
        self.ranking_list_Bottom_td_0_xuhao.setMinimumSize(QtCore.QSize(90, 40))
        self.ranking_list_Bottom_td_0_xuhao.setMaximumSize(QtCore.QSize(90, 40))
        self.ranking_list_Bottom_td_0_xuhao.setStyleSheet("")
        self.ranking_list_Bottom_td_0_xuhao.setAlignment(QtCore.Qt.AlignCenter)
        self.ranking_list_Bottom_td_0_xuhao.setObjectName("ranking_list_Bottom_td_0_xuhao")
        self.horizontalLayout_frame_song_list_list_bottom_lable.addWidget(self.ranking_list_Bottom_td_0_xuhao)
        self.ranking_list_Bottom_td_0_so_name = QtWidgets.QPushButton(self.ranking_list_Bottom_td_0)
        self.ranking_list_Bottom_td_0_so_name.setMinimumSize(QtCore.QSize(440, 40))
        self.ranking_list_Bottom_td_0_so_name.setMaximumSize(QtCore.QSize(440, 40))
        self.ranking_list_Bottom_td_0_so_name.setStyleSheet("text-align :left;")
        self.ranking_list_Bottom_td_0_so_name.setObjectName("ranking_list_Bottom_td_0_so_name")
        self.horizontalLayout_frame_song_list_list_bottom_lable.addWidget(self.ranking_list_Bottom_td_0_so_name)
        self.ranking_list_Bottom_td_0_Bt = QtWidgets.QFrame(self.ranking_list_Bottom_td_0)
        self.ranking_list_Bottom_td_0_Bt.setMinimumSize(QtCore.QSize(340, 40))
        self.ranking_list_Bottom_td_0_Bt.setMaximumSize(QtCore.QSize(340, 40))
        self.ranking_list_Bottom_td_0_Bt.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    border-radius:10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 10pt \"本墨字语\";\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 174, 254, 255), stop:1 rgba(149, 209, 214, 255));\n"
"border: 1px solid  qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(161, 174, 255, 255), stop:0.863636 rgba(74, 129, 230, 255));\n"
"}\n"
"QPushButton:hover{  \n"
"    color: rgb(213, 8, 8);\n"
"    padding-bottom:3px; \n"
"}\n"
"QPushButton:focus {\n"
"      color: rgb(255, 255, 255);\n"
"      outline: 0px;\n"
"    }\n"
"QPushButton:pressed{\n"
"    background-color: rgb(200, 200, 200);\n"
"    color: rgb(255, 149, 0);\n"
"}\n"
"")
        self.ranking_list_Bottom_td_0_Bt.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ranking_list_Bottom_td_0_Bt.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ranking_list_Bottom_td_0_Bt.setObjectName("ranking_list_Bottom_td_0_Bt")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.ranking_list_Bottom_td_0_Bt)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ranking_list_Bottom_td_0_Bt_play = QtWidgets.QPushButton(self.ranking_list_Bottom_td_0_Bt)
        self.ranking_list_Bottom_td_0_Bt_play.setMinimumSize(QtCore.QSize(0, 25))
        self.ranking_list_Bottom_td_0_Bt_play.setMaximumSize(QtCore.QSize(90, 25))
        self.ranking_list_Bottom_td_0_Bt_play.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ranking_list_Bottom_td_0_Bt_play.setIcon(icon)
        self.ranking_list_Bottom_td_0_Bt_play.setIconSize(QtCore.QSize(12, 12))
        self.ranking_list_Bottom_td_0_Bt_play.setObjectName("ranking_list_Bottom_td_0_Bt_play")
        self.horizontalLayout_4.addWidget(self.ranking_list_Bottom_td_0_Bt_play)
        self.ranking_list_Bottom_td_0_Bt_collect = QtWidgets.QPushButton(self.ranking_list_Bottom_td_0_Bt)
        self.ranking_list_Bottom_td_0_Bt_collect.setMinimumSize(QtCore.QSize(0, 25))
        self.ranking_list_Bottom_td_0_Bt_collect.setMaximumSize(QtCore.QSize(90, 25))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/add_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ranking_list_Bottom_td_0_Bt_collect.setIcon(icon1)
        self.ranking_list_Bottom_td_0_Bt_collect.setIconSize(QtCore.QSize(20, 20))
        self.ranking_list_Bottom_td_0_Bt_collect.setObjectName("ranking_list_Bottom_td_0_Bt_collect")
        self.horizontalLayout_4.addWidget(self.ranking_list_Bottom_td_0_Bt_collect)
        self.ranking_list_Bottom_td_0_Bt_load = QtWidgets.QPushButton(self.ranking_list_Bottom_td_0_Bt)
        self.ranking_list_Bottom_td_0_Bt_load.setMinimumSize(QtCore.QSize(0, 25))
        self.ranking_list_Bottom_td_0_Bt_load.setMaximumSize(QtCore.QSize(90, 25))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ranking_list_Bottom_td_0_Bt_load.setIcon(icon2)
        self.ranking_list_Bottom_td_0_Bt_load.setObjectName("ranking_list_Bottom_td_0_Bt_load")
        self.horizontalLayout_4.addWidget(self.ranking_list_Bottom_td_0_Bt_load)
        self.horizontalLayout_frame_song_list_list_bottom_lable.addWidget(self.ranking_list_Bottom_td_0_Bt)
        self.verticalLayout_song_list_bottom.addWidget(self.ranking_list_Bottom_td_0)
        self.ranking_list_Bottom_td_1 = QtWidgets.QFrame(self.ranking_list_Bottom)
        self.ranking_list_Bottom_td_1.setMinimumSize(QtCore.QSize(0, 40))
        self.ranking_list_Bottom_td_1.setMaximumSize(QtCore.QSize(16777215, 40))
        self.ranking_list_Bottom_td_1.setStyleSheet("QFrame,QLabel,QPushButton,QRadioButton{border:none;background-color:rgb(247, 248, 255)}\n"
"\n"
"QPushButton:hover{  \n"
"    color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(162, 179, 255, 255), stop:1 rgba(144, 228, 137, 255));\n"
"}")
        self.ranking_list_Bottom_td_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ranking_list_Bottom_td_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ranking_list_Bottom_td_1.setObjectName("ranking_list_Bottom_td_1")
        self.horizontalLayout_frame_song_list_bottom_inf = QtWidgets.QHBoxLayout(self.ranking_list_Bottom_td_1)
        self.horizontalLayout_frame_song_list_bottom_inf.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_frame_song_list_bottom_inf.setSpacing(0)
        self.horizontalLayout_frame_song_list_bottom_inf.setObjectName("horizontalLayout_frame_song_list_bottom_inf")
        self.ranking_list_Bottom_td_1_no = QtWidgets.QLabel(self.ranking_list_Bottom_td_1)
        self.ranking_list_Bottom_td_1_no.setMinimumSize(QtCore.QSize(40, 40))
        self.ranking_list_Bottom_td_1_no.setMaximumSize(QtCore.QSize(40, 40))
        self.ranking_list_Bottom_td_1_no.setStyleSheet("")
        self.ranking_list_Bottom_td_1_no.setAlignment(QtCore.Qt.AlignCenter)
        self.ranking_list_Bottom_td_1_no.setObjectName("ranking_list_Bottom_td_1_no")
        self.horizontalLayout_frame_song_list_bottom_inf.addWidget(self.ranking_list_Bottom_td_1_no)
        self.ranking_list_Bottom_td_1_choice = QtWidgets.QRadioButton(self.ranking_list_Bottom_td_1)
        self.ranking_list_Bottom_td_1_choice.setMinimumSize(QtCore.QSize(40, 40))
        self.ranking_list_Bottom_td_1_choice.setMaximumSize(QtCore.QSize(40, 40))
        self.ranking_list_Bottom_td_1_choice.setText("")
        self.ranking_list_Bottom_td_1_choice.setChecked(True)
        self.ranking_list_Bottom_td_1_choice.setObjectName("ranking_list_Bottom_td_1_choice")
        self.horizontalLayout_frame_song_list_bottom_inf.addWidget(self.ranking_list_Bottom_td_1_choice)
        self.ranking_list_Bottom_td_1_name = QtWidgets.QPushButton(self.ranking_list_Bottom_td_1)
        self.ranking_list_Bottom_td_1_name.setMinimumSize(QtCore.QSize(270, 40))
        self.ranking_list_Bottom_td_1_name.setMaximumSize(QtCore.QSize(540, 40))
        self.ranking_list_Bottom_td_1_name.setToolTipDuration(-1)
        self.ranking_list_Bottom_td_1_name.setStyleSheet("text-align :left;")
        self.ranking_list_Bottom_td_1_name.setObjectName("ranking_list_Bottom_td_1_name")
        self.horizontalLayout_frame_song_list_bottom_inf.addWidget(self.ranking_list_Bottom_td_1_name)
        self.ranking_list_Bottom_td_1_play = QtWidgets.QPushButton(self.ranking_list_Bottom_td_1)
        self.ranking_list_Bottom_td_1_play.setMinimumSize(QtCore.QSize(40, 40))
        self.ranking_list_Bottom_td_1_play.setMaximumSize(QtCore.QSize(40, 40))
        self.ranking_list_Bottom_td_1_play.setText("")
        self.ranking_list_Bottom_td_1_play.setIcon(icon)
        self.ranking_list_Bottom_td_1_play.setIconSize(QtCore.QSize(13, 13))
        self.ranking_list_Bottom_td_1_play.setObjectName("ranking_list_Bottom_td_1_play")
        self.horizontalLayout_frame_song_list_bottom_inf.addWidget(self.ranking_list_Bottom_td_1_play)
        self.ranking_list_Bottom_td_1_download = QtWidgets.QPushButton(self.ranking_list_Bottom_td_1)
        self.ranking_list_Bottom_td_1_download.setMinimumSize(QtCore.QSize(40, 40))
        self.ranking_list_Bottom_td_1_download.setMaximumSize(QtCore.QSize(40, 40))
        self.ranking_list_Bottom_td_1_download.setText("")
        self.ranking_list_Bottom_td_1_download.setIcon(icon2)
        self.ranking_list_Bottom_td_1_download.setIconSize(QtCore.QSize(18, 18))
        self.ranking_list_Bottom_td_1_download.setObjectName("ranking_list_Bottom_td_1_download")
        self.horizontalLayout_frame_song_list_bottom_inf.addWidget(self.ranking_list_Bottom_td_1_download)
        self.verticalLayout_song_list_bottom.addWidget(self.ranking_list_Bottom_td_1)
        self.ranking_list_Bottom_td_2 = QtWidgets.QFrame(self.ranking_list_Bottom)
        self.ranking_list_Bottom_td_2.setMinimumSize(QtCore.QSize(0, 40))
        self.ranking_list_Bottom_td_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.ranking_list_Bottom_td_2.setStyleSheet("QFrame,QLabel,QPushButton,QRadioButton{border:none;background-color:rgb(237, 238, 255)}\n"
"QPushButton:hover{  \n"
"    color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(162, 179, 255, 255), stop:1 rgba(144, 228, 137, 255));\n"
"}")
        self.ranking_list_Bottom_td_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ranking_list_Bottom_td_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ranking_list_Bottom_td_2.setObjectName("ranking_list_Bottom_td_2")
        self.horizontalLayout_frame_song_list_bottom_inf_2 = QtWidgets.QHBoxLayout(self.ranking_list_Bottom_td_2)
        self.horizontalLayout_frame_song_list_bottom_inf_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_frame_song_list_bottom_inf_2.setSpacing(0)
        self.horizontalLayout_frame_song_list_bottom_inf_2.setObjectName("horizontalLayout_frame_song_list_bottom_inf_2")
        self.ranking_list_Bottom_td_2_no = QtWidgets.QLabel(self.ranking_list_Bottom_td_2)
        self.ranking_list_Bottom_td_2_no.setMinimumSize(QtCore.QSize(40, 40))
        self.ranking_list_Bottom_td_2_no.setMaximumSize(QtCore.QSize(40, 40))
        self.ranking_list_Bottom_td_2_no.setStyleSheet("")
        self.ranking_list_Bottom_td_2_no.setAlignment(QtCore.Qt.AlignCenter)
        self.ranking_list_Bottom_td_2_no.setObjectName("ranking_list_Bottom_td_2_no")
        self.horizontalLayout_frame_song_list_bottom_inf_2.addWidget(self.ranking_list_Bottom_td_2_no)
        self.ranking_list_Bottom_td_2_choice = QtWidgets.QRadioButton(self.ranking_list_Bottom_td_2)
        self.ranking_list_Bottom_td_2_choice.setMinimumSize(QtCore.QSize(40, 40))
        self.ranking_list_Bottom_td_2_choice.setMaximumSize(QtCore.QSize(40, 40))
        self.ranking_list_Bottom_td_2_choice.setText("")
        self.ranking_list_Bottom_td_2_choice.setChecked(True)
        self.ranking_list_Bottom_td_2_choice.setObjectName("ranking_list_Bottom_td_2_choice")
        self.horizontalLayout_frame_song_list_bottom_inf_2.addWidget(self.ranking_list_Bottom_td_2_choice)
        self.ranking_list_Bottom_td_2_name = QtWidgets.QPushButton(self.ranking_list_Bottom_td_2)
        self.ranking_list_Bottom_td_2_name.setMinimumSize(QtCore.QSize(270, 40))
        self.ranking_list_Bottom_td_2_name.setMaximumSize(QtCore.QSize(540, 40))
        self.ranking_list_Bottom_td_2_name.setStyleSheet("text-align :left;")
        self.ranking_list_Bottom_td_2_name.setObjectName("ranking_list_Bottom_td_2_name")
        self.horizontalLayout_frame_song_list_bottom_inf_2.addWidget(self.ranking_list_Bottom_td_2_name)
        self.ranking_list_Bottom_td_2_play = QtWidgets.QPushButton(self.ranking_list_Bottom_td_2)
        self.ranking_list_Bottom_td_2_play.setMinimumSize(QtCore.QSize(40, 40))
        self.ranking_list_Bottom_td_2_play.setMaximumSize(QtCore.QSize(40, 40))
        self.ranking_list_Bottom_td_2_play.setText("")
        self.ranking_list_Bottom_td_2_play.setIcon(icon)
        self.ranking_list_Bottom_td_2_play.setIconSize(QtCore.QSize(13, 13))
        self.ranking_list_Bottom_td_2_play.setObjectName("ranking_list_Bottom_td_2_play")
        self.horizontalLayout_frame_song_list_bottom_inf_2.addWidget(self.ranking_list_Bottom_td_2_play)
        self.ranking_list_Bottom_td_2_download = QtWidgets.QPushButton(self.ranking_list_Bottom_td_2)
        self.ranking_list_Bottom_td_2_download.setMinimumSize(QtCore.QSize(40, 40))
        self.ranking_list_Bottom_td_2_download.setMaximumSize(QtCore.QSize(40, 40))
        self.ranking_list_Bottom_td_2_download.setText("")
        self.ranking_list_Bottom_td_2_download.setIcon(icon2)
        self.ranking_list_Bottom_td_2_download.setIconSize(QtCore.QSize(18, 18))
        self.ranking_list_Bottom_td_2_download.setObjectName("ranking_list_Bottom_td_2_download")
        self.horizontalLayout_frame_song_list_bottom_inf_2.addWidget(self.ranking_list_Bottom_td_2_download)
        self.verticalLayout_song_list_bottom.addWidget(self.ranking_list_Bottom_td_2)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_song_list_bottom.addItem(spacerItem)
        self.verticalLayout.addWidget(self.ranking_list_Bottom)

        self.retranslateUi(ranking_list)
        self.ranking_list_Bottom_td_1_name.clicked.connect(self.ranking_list_Bottom_td_1_choice.click)
        self.ranking_list_Bottom_td_2_name.clicked.connect(self.ranking_list_Bottom_td_2_choice.click)
        QtCore.QMetaObject.connectSlotsByName(ranking_list)

    def retranslateUi(self, ranking_list):
        _translate = QtCore.QCoreApplication.translate
        ranking_list.setWindowTitle(_translate("ranking_list", "Form"))
        self.ranking_list_Top_na_Label.setText(_translate("ranking_list", "飙升榜"))
        self.ranking_list_Bottom_td_0_xuhao.setText(_translate("ranking_list", "序号"))
        self.ranking_list_Bottom_td_0_so_name.setText(_translate("ranking_list", "歌曲"))
        self.ranking_list_Bottom_td_0_Bt_play.setText(_translate("ranking_list", "播放列表"))
        self.ranking_list_Bottom_td_0_Bt_collect.setText(_translate("ranking_list", "收藏歌单"))
        self.ranking_list_Bottom_td_0_Bt_load.setText(_translate("ranking_list", "下载列表"))
        self.ranking_list_Bottom_td_1_no.setText(_translate("ranking_list", "1"))
        self.ranking_list_Bottom_td_1_name.setToolTip(_translate("ranking_list", "<html><head/><body><p><span style=\" font-size:8pt; font-family:\'本墨字语\'\">adfs发顺丰的法人个人</span></p></body></html>"))
        self.ranking_list_Bottom_td_1_name.setWhatsThis(_translate("ranking_list", "<html><head/>p { border-top-style:dotted; border-right-style:solid; border-bottom-style:dotted; border-left-style:solid; }<body><p><br/>asss</p></body></html>"))
        self.ranking_list_Bottom_td_1_name.setText(_translate("ranking_list", "发发发发发发付付付付付付"))
        self.ranking_list_Bottom_td_2_no.setText(_translate("ranking_list", "2"))
        self.ranking_list_Bottom_td_2_name.setToolTip(_translate("ranking_list", "<html><head/><body><p>ddddddddddddddddddd</p></body></html>"))
        self.ranking_list_Bottom_td_2_name.setText(_translate("ranking_list", "asdddddddddddddddddddddddddddddddddddddddddddddddddddddddd"))
import icon_rc
